version: 2
jobs:
  build:
    docker:
      - image: openjdk:8-jdk
    working_directory: ~/app
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - checkout
      - run: chmod +x gradlew

      - restore_cache:
          keys:
            - v1-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Plugin.kt" }}-{{ checksum "buildSrc/src/main/kotlin/Lib.kt" }}
            - v1-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Plugin.kt" }}
            - v1-{{ checksum "build.gradle.kts" }}
            - v1-

      - run: ./gradlew dependencies

      - save_cache:
          key: v1-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Plugin.kt" }}-{{ checksum "buildSrc/src/main/kotlin/Lib.kt" }}
          paths:
            - ~/.gradle

      - run:
          command: ./gradlew test
          name: Running unit tests
          when: always

      - store_test_results:
          path: build/test-results
