version: 2
jobs:
  build:
    docker:
    - image: fbrissi/maven-openjfx:jdk-8
    working_directory: ~/app
    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-{{ checksum "pom.xml" }}
        - v1-
        paths:
        - ~/.m2
    - run:
        command: |
          mkdir ~/android
          cd ~/android
          wget -q https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz -O android-sdk.tgz
          tar -xvzf android-sdk.tgz --no-same-owner
          rm -f android-sdk.tgz
          export PATH=$PATH:~/android/android-sdk-linux/tools
          export PATH=$PATH:~/android/android-sdk-linux/platform-tools
          export ANDROID_HOME=~/android/android-sdk-linux
          echo y | android update sdk --no-ui --all --filter platform-tools | grep 'package installed'
          echo y | android update sdk --no-ui --all --filter android-19 | grep 'package installed'
          cd ~
          git clone https://github.com/simpligility/maven-android-sdk-deployer.git sdk-deployer
          cd sdk-deployer
          mvn install -P 4.4 || true
          cd ~/app
        name: Retrieving android core library
        when: always
    - run:
        command: mvn -U test
        name: Running unit tests
        when: always
    - deploy:
        command: |
          mkdir -p target/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} target/junit/ \;
        name: Copy test artifacts
    - store_test_results:
        path: target/junit/
    - store_artifacts:
        path: target/junit/

    - deploy:
        command: mvn site -P report
        name: Building reports
    - store_artifacts:
        path: target/site/

    - save_cache:
        key: v1-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2
